import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import javax.swing.text.MaskFormatter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusAdapter;


public class RegistrationForm extends JFrame {

	private JTextField usernameField, userIDField, phoneField, dobField, emailField,icField;
	private JComboBox<String> departmentComboBox;
	private JButton signUpButton, backButton;
	private JPasswordField passwordField;

    //constructor
    public RegistrationForm() {
        // Set Frame Properties
        setTitle("Registration Form");
        setSize(574, 550);
		setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		setResizable(false);
		getContentPane().setBackground(new Color (173, 216, 230));
		setLayout(null);

        // Create components
        JLabel welcomeLabel = new JLabel("Employee", JLabel.CENTER);
		JLabel titleLabel = new JLabel("Registration details", JLabel.CENTER);
		
		JLabel usernameLabel = new JLabel("Username:");
        usernameField = new JTextField();

		JLabel userIDLabel = new JLabel("User ID:");
        userIDField = new JTextField();
        usernameField.setToolTipText("Your Name");

        JLabel icLabel = new JLabel("IC:");
        icField = new JTextField();
        icField.setToolTipText("Identity Card Number E.g. 031231041234");

        JLabel phoneLabel = new JLabel("Phone Number:");
        phoneField = new JTextField();
        phoneField.setToolTipText("Mobile Phone E.g. 0123355779");

        JLabel dobLabel = new JLabel("Date of Birth:");

        JLabel departmentLabel = new JLabel("Department:");
        departmentComboBox = new JComboBox<>(new String[]{"IT Department", "Marketing Department", "Accounting Department", "Human Resources Department"});

        JLabel emailLabel = new JLabel("Email:");
        emailField = new JTextField();

        JLabel passwordLabel = new JLabel("Password:");
        passwordField = new JPasswordField();

        signUpButton = new JButton("Sign Up");
        backButton = new JButton("Back to Login Page");
        
        // Add components to the frame using setBounds
        add(welcomeLabel);
        welcomeLabel.setBounds(168, 20, 240, 18);
		welcomeLabel.setFont(new Font("SansSerif", 1, 16));
		add(titleLabel);
        titleLabel.setBounds(177, 40, 240, 18);
		titleLabel.setFont(new Font("SansSerif", 1, 12));
		
		add(usernameLabel);
        usernameLabel.setBounds(120, 90, 76, 16);
        add(usernameField);
        usernameField.setBounds(252, 90, 172, 22);
        //userID get autogenerated based on username everytime the focus is lost
		usernameField.addFocusListener(new FocusAdapter() { 
            @Override
            public void focusLost(FocusEvent e){
                userIDField.setText(generateUserId(usernameField.getText()));
            }
        });
        
		add(userIDLabel);
        userIDLabel.setBounds(122, 136, 76, 16);
        add(userIDField);
        userIDField.setBounds(252, 133, 172, 22);
		userIDField.setText(generateUserId("")); //set the autogeneratedID to the userIDField
        userIDField.setEditable(false); //not allowed to edit userID textfield

        add(icLabel);
        icLabel.setBounds(122, 176, 97, 16);
        add(icField);
        icField.setBounds(252, 173, 172, 22);

        add(phoneLabel);
        phoneLabel.setBounds(122, 216, 97, 16);
        add(phoneField);
        phoneField.setBounds(252, 213, 172, 22);

        add(dobLabel);
        dobLabel.setBounds(122, 256, 97, 16);
		try{
			MaskFormatter maskFormatter = new MaskFormatter("##/##/####");
			dobField = new JFormattedTextField(maskFormatter);
		}catch(Exception e){
			e.printStackTrace();
		}
		add(dobField);
		dobField.setBounds (252, 253, 172, 22);
        dobField.setToolTipText("dd/MM/yyyy");
		
        add(departmentLabel);
        departmentLabel.setBounds(122, 296, 97, 16);
        add(departmentComboBox);
        departmentComboBox.setBounds(252, 293, 172, 22);

        add(emailLabel);
        emailLabel.setBounds(122, 336, 89, 16);
        add(emailField);
        emailField.setBounds(252, 333, 172, 22);

        add(passwordLabel);
        passwordLabel.setBounds(122, 376, 89, 16);
        add(passwordField);
        passwordField.setBounds(252, 373, 172, 22);

        add(signUpButton);
        signUpButton.setBounds(110, 420, 320, 23);
		signUpButton.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent e){
                if (validateRegistration()){
                    if(addRegisterInfo()){
                        JOptionPane.showMessageDialog(RegistrationForm.this, "Register successfully. Please Remember Your UserID\n"+userIDField.getText());
                        clearFields();
                    }
                    else{
                        JOptionPane.showMessageDialog(RegistrationForm.this, "Error registering. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
			}
	    });

        add(backButton);
        backButton.setBounds(270, 460, 160, 23);
		backButton.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent e){
				openLoginPage();
			}
		});

        setVisible (true);
    }

    //check form input 
    private boolean validateRegistration() {
        //Ensure no empty fields
        if (usernameField.getText().trim().isEmpty() ||
        userIDField.getText().trim().isEmpty() ||
        icField.getText().trim().isEmpty() ||
        phoneField.getText().trim().isEmpty() ||
        dobField.getText().trim().isEmpty() ||
        departmentComboBox.getSelectedIndex() == -1 ||
        emailField.getText().trim().isEmpty() ||
        passwordField.getPassword().length==0) {
            JOptionPane.showMessageDialog(RegistrationForm.this, "Please fill in all fields.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // IC Number validation: exactly 12 digits
        String ICRegex = "\\d{12}";
        if (!icField.getText().matches(ICRegex)) {
            JOptionPane.showMessageDialog(RegistrationForm.this, "IC Number must be exactly 12 digits.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Phone Number validation: 10 to 11 digits
        String phoneRegex = "\\d{10,11}";
        if (!phoneField.getText().matches(phoneRegex)) {
            JOptionPane.showMessageDialog(RegistrationForm.this, "Phone Number must be 10 to 11 digits.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Email validation
        String emailRegex = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}";
        if (!emailField.getText().matches(emailRegex)) {
            JOptionPane.showMessageDialog(RegistrationForm.this, "Email format is invalid.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // If all fields are valid
        return true;
    }
	
	//add register info into registerInfo.txt
	private boolean addRegisterInfo(){
		// Get values from the fields
		String username = usernameField.getText();
		String userID = userIDField.getText();
        String IC = icField.getText();
        String phone = phoneField.getText();
        String dob = dobField.getText();
        String department = (String) departmentComboBox.getSelectedItem();
        String email = emailField.getText();
        String password = new String(passwordField.getPassword());

        //Append into file
        try (FileWriter fileWriter = new FileWriter("registerInfo.txt", true))
        {
            fileWriter.write(username + "\t" + userID + "\t"+ IC + "\t" + phone + "\t" + dob + 
			"\t" + department + "\t" + email + "\t" + password + "\n");
			fileWriter.close();
            return true;
		}catch(IOException e){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Failed to save information", "Error", JOptionPane.ERROR_MESSAGE);
			e.printStackTrace();
			return false;
		}
	}
    
    //Autogenerate a random userID based on User name
    private String generateUserId(String username) {
        // Extract initials from the name
        StringBuilder initials = new StringBuilder();
        String[] words = username.split("\\s+");
        if (username != null) {
            for (String word : words) {
                if (!word.isEmpty()) {
                    initials.append(word.charAt(0));
                }
            }
        }
        // Generate a random number between 1000 and 9999
        Random random = new Random();
        int randomNumber = random.nextInt(9000) + 1000;

        // Combine initials with the random number
        return initials.toString().toUpperCase() + randomNumber;
    }

	//clearFields
    private void clearFields() {
        usernameField.setText("");
		userIDField.setText("");
        icField.setText("");
        phoneField.setText("");
        dobField.setText("");
        departmentComboBox.setSelectedIndex(0);
        emailField.setText("");
        passwordField.setText(""); 
    }
	
    // back to login page
	 private void openLoginPage() {
        Login loginpage = new Login();
		loginpage.setVisible(true);
		// Close the current registrationForm
		this.dispose();
    }
}

